### PR TITLE
Added very basic sound functionality.

### PR DESCRIPTION
**Pull request by skyem123**
This is very limited, but it _should_ work.

### CODE REVIEW

**Comment by RX14** [comment]
"should work" did you test it?

**Comment by skyem123** [comment]
^^;;;
I don't know how to test it, but I was talking to @calclavia when I was coding this and he said that it should be OK.

**Comment by RX14** [comment]
Well you try and use it in novaexample and test if it works.

**Comment by skyem123** [comment]
@RX14, well, @calclavia did this in ddf7881e6a472193e1e81e4bfb51e12e0b55a21c, so why don't you shout at him?

**Pull request closed without merging**
