### PR TITLE
Added icons (Item) to the category.

### PR DESCRIPTION
**Pull request by halvors**
See Nova-Team/NOVA-Core#113

### CODE REVIEW

**Comment by calclavia** [comment]
FAILED! Fix it!

**Comment by halvors** [comment]
Umm. This is building just fine in the IDEA.

**Comment by halvors** [comment]
It's failing because that NOVA-Wrapper-MC is cloning "git clone https://github.com/NOVAAPI/NovaCore/" not the branch that has my NOVA-Core changes. Thereby the build fails.

**Comment by RX14** [comment]
Not quite true

**Comment by halvors** [comment]
@RX14 What do you mean?

**Comment by RX14** [comment]
It's breaking on my machine too

**Comment by halvors** [comment]
Um. How? Sure you have the changes to NOVA-Core as well?

**Comment by RX14** [comment]
I'm sure.

**Comment by halvors** [comment]
Could you send me the error you're getting?

**Comment by RX14** [comment]
Nah it was just gradle failing...

**Comment by Victorious3** [comment]
I would rather have it pick the first item that you register as default, and allow to register an icon for the category instead. This is too focused on Minecraft imo.

**Comment by halvors** [comment]
That's still the default behaviour.  And yes this is focused on minecraft at the moment. Item should be replaced with some sort of Icon in the future. But this implements the possibility to pick the icon/item that should be used.

**Comment by halvors** [comment]
@Victorious3 If you have an idea how to hack around that Minecraft expects an item and supply the wrapper with an Icon instead please do :-)

**Comment by Victorious3** [comment]
There are ways to do everything, don't even need hacks for it as you can simply use a dummy item + item renderer. Don't know about 1.8.

**Comment by calclavia** [comment]
@Victorious3 1.8 hasn't changed for creative tabs at all.

**Comment by Victorious3** [comment]
@calclavia Yeah, but the item renderer?

**Comment by calclavia** [comment]
Creative tabs don't need to touch item renderer, they only need to know which item is representative of the tab.

**Comment by Victorious3** [comment]
@calclavia 
> I would rather have it pick the first item that you register as default, and allow to register an icon for the category instead. This is too focused on Minecraft imo.

**Pull request merged**
